### ISSUE TITLE
Личное

### ISSUE THREAD

**Issue by ihabibullin** [adlordy/report-generator#1]
Нужно что бы можно было маркировать определенные тайтлы как Личное. При этом при формировании отчета эти тайтлы не должны учитываться.

Желательно так же в каком то виде видеть сколько времени ушло на личные тайтлы.

**Comment by adlordy** [comment]
- [x] Добавить фиксированный проект в мои проекты с именем Личное и идентификатором 0
- [x] Дать возможность добавить заголовки в этот проект без выбора типа работ
- [x] Считать заголовки с этим типом проекта и отображать отдельно под основным отчетом
