### ISSUE TITLE
Размазывание

### ISSUE THREAD

**Issue by ihabibullin** [adlordy/report-generator#2]
Наша система допускает ввод данных градиентом по 15 мин = 0,25 часа. Соответственно при формировании отчета время должно быть с шагом 0,25.

Так же обязательно мы должны списать рабочий день = 8 часов. Поэтому если за вычетом "Личное"  к списанию всего 6 часов, то все строки надо пропорционально увеличить, что бы на выходе было 8 часов.

**Comment by adlordy** [comment]
**Алгоритм**
1. Считаем заголовки и получаем общее время по каждому проекту в секундах.
2. Личное считаем и отображаем как есть, в дальнейших расчётах не учитываем 
3. Суммируем полученные категории 
4. Фактор = сумма / (3600*8)
5. Значение в каждой категории делим на фактор, получаем масштабиронное значение
6. Далее нужно округлить до 900 секунд каждое масштабиронное значение. 
7. Считаем сумму если для всех значений сделать floor. Разница между этим числом и 8 часами дает количество значений которые нужно увеличить (ceiling), остальные уменьшить (floor).
