### ISSUE TITLE
Общее

### ISSUE THREAD

**Issue by ihabibullin** [adlordy/report-generator#3]
Так или иначе встречаются окны у которых тайтл всегда одинаковый. Например в ватсапп. У меня в ватсапп по многим проектам есть отдельные группы, но увы имя группы не транслируется в тайтл окна. Поэтому необходимо ввести категорию Общее.

При формировании отчета Общее распределять по всем строкам в отчете.

**Comment by adlordy** [comment]
Альтернатива. Придумать способ получать более точную информацию о контексте для конкретных приложений

**Comment by adlordy** [comment]
Не уверен в полезности этого функционала.
