### ISSUE TITLE
Выбор даты или интервала дат для формирования отчета(-ов)

### ISSUE THREAD

**Issue by ihabibullin** [adlordy/report-generator#5]
Реализовать возможность выбора даты или интервала дат, за который надо сформировать отчет. При этом тайтлы так же должны зажаться по этим датам.

Так будет значительно проще понять как работает система:
Я смогу быстро разобрать тайтлы за сегодня и проверить получившийся отчет.

Спасибо.

**Comment by adlordy** [comment]
Implemented on my-titles page in [date branch](/adlordy/report-generator/tree/date)
