### ISSUE TITLE
Корректировка правил округления

### ISSUE THREAD

**Issue by ihabibullin** [adlordy/report-generator#9]
минимальное удельное значение должно округляться в 15 минут. Остальное должно пересчитываться с учетом этого.

Например, если работа по проекту удельно округлилась в 0, то значение должно стать 15 мин (0,25ч.), а на остальные задачи должны размазываться из расчета 8-0,25.

Спасибо.

**Comment by adlordy** [comment]
Closed by 96bcb71bf
